// Word Wrangler - Target Word Generator for Bookworm-style gameplay
// Generates a board with 20 embeddable target words that can actually be found

const WORD_POOL = [
  // 3-letter words
  'CAT','DOG','SUN','MOON','STAR','TREE','BIRD','FISH','BOOK','PEN','CUP','HAT','BOX','KEY','MAP','CLOCK','BALL','BAT','BED','CHAIR','TABLE','DOOR','WINDOW','FLOOR','WALL','ROOF','PATH','ROAD','RIVER','LAKE','OCEAN','MOUNTAIN','HILL','VALLEY','FOREST','DESERT','GARDEN','FLOWER','LEAF','GRASS','FRUIT','APPLE','ORANGE','BANANA','GRAPE','BERRY','MELON','PEACH','PLUM','CHERRY','LEMON','LIME','CORNUCOPIA','HARVEST','AUTUMN','WINTER','SPRING','SUMMER','SEASON','WEATHER','RAIN','SNOW','WIND','STORM','CLOUD','THUNDER','LIGHTNING','SUNSHINE','SHADOW','LIGHT','DARK','DAY','NIGHT','MORNING','EVENING','AFTERNOON','MIDNIGHT','NOON','HOUR','MINUTE','SECOND','TIME','YEAR','MONTH','WEEK','TODAY','TOMORROW','YESTERDAY','NOW','SOON','LATER','EARLY','LATE','FAST','SLOW','QUICK','RAPID','SWIFT','SPEED','PACE','RUN','WALK','JUMP','LEAP','HOP','SKIP','STEP','CLIMB','FALL','RISE','DROP','FLY','SWIM','DIVE','FLOAT','SINK','DRIFT','FLOW','STREAM','CURRENT','TIDE','WAVE','SURGE','SWELL','GUSH','POUR','DRIP','SPRAY','SPLASH','SPILL','LEAK','FLOOD','DROUGHT','DRY','WET','DAMP','MOIST','HUMID','ARID','BARREN','FERTILE','RICH','POOR','WEALTH','MONEY','GOLD','SILVER','BRONZE','COPPER','IRON','STEEL','METAL','STONE','ROCK','SAND','DUST','DIRT','MUD','CLAY','SOIL','EARTH','GROUND','LAND','TERRAIN','SOIL','PLOT','FIELD','MEADOW','PASTURE','RANCH','FARM','CROP','HARVEST','YIELD','SEED','PLANT','GROW','BLOOM','BLOSSOM','BUD','PETAL','STEM','ROOT','BRANCH','TRUNK','BARK','WOOD','TIMBER','LOG','PLANK','BOARD','BEAM','POST','POLE','STICK','ROD','BAR','WIRE','CABLE','ROPE','STRING','THREAD','CORD','CHAIN','LINK','KNOT','LOOP','CIRCLE','SQUARE','TRIANGLE','RECTANGLE','OVAL','DIAMOND','SHAPE','FORM','FIGURE','PATTERN','DESIGN','STYLE','MODE','FASHION','TREND','LOOK','APPEARANCE','IMAGE','PICTURE','PHOTO','DRAWING','PAINTING','SKETCH','ART','ARTIST','CREATOR','MAKER','BUILDER','DESIGNER','PLANNER','WRITER','AUTHOR','POET','SONG','MUSIC','MELODY','TUNE','RHYTHM','BEAT','TEMPO','NOTE','CHORD','HARMONY','SOUND','NOISE','VOICE','SPEECH','WORD','LANGUAGE','TONGUE','DIALECT','ACCENT','PRONUNCIATION','SPELLING','GRAMMAR','SYNTAX','SENTENCE','PHRASE','CLAUSE','PARAGRAPH','CHAPTER','BOOK','NOVEL','STORY','TALE','NARRATIVE','PLOT','CHARACTER','HERO','VILLAIN','PROTAGONIST','ANTAGONIST','SETTING','SCENE','ACT','PLAY','DRAMA','COMEDY','TRAGEDY','FILM','MOVIE','CINEMA','THEATER','STAGE','SCREEN','ACTOR','ACTRESS','PERFORMER','ROLE','PART','CAST','CREW','DIRECTOR','PRODUCER','WRITER','SCRIPT','SCENARIO','DIALOGUE','MONOLOGUE','SPEECH','LINE','WORD','LETTER','ALPHABET','VOWEL','CONSONANT','SYLLABLE','PRONUNCIATION','ENUNCIATION','ARTICULATION','EXPRESSION','DECLARATION','STATEMENT','ANNOUNCEMENT','PROCLAMATION','NOTICE','WARNING','ALERT','SIGNAL','SIGN','SYMBOL','MARK','INDICATOR','LABEL','TAG','BADGE','EMBLEM','LOGO','BRAND','TRADEMARK','NAME','TITLE','HEADING','CAPTION','SUBTITLE','FOOTNOTE','REFERENCE','CITATION','SOURCE','ORIGIN','BEGINNING','START','COMMENCEMENT','INITIATION','LAUNCH','OPENING','INTRODUCTION','PREFACE','FOREWORD','PROLOGUE','PREAMBLE','PRELUDE','OVERTURE','INTRO','ENTRY','ENTRANCE','EXIT','DEPARTURE','LEAVING','ARRIVAL','ADVENT','COMING','RETURN','RECOVERY','RESTORATION','RENEWAL','REVIVAL','RESURRECTION','REBIRTH','REGENERATION','REJUVENATION','REFRESH','RELOAD','RESTART','RESET','CLEAR','ERASE','DELETE','REMOVE','ELIMINATE','DESTROY','DEMOLISH','RAZE','WRECK','RUIN','DEVASTATE','RAVAGE','PILLAGE','PLUNDER','LOOT','SACK','RAID','ATTACK','ASSAULT','STRIKE','HIT','SMASH','CRASH','BANG','SLAM','THUMP','THUD','BUMP','KNOCK','TAP','PAT','POKE','PROD','NUDGE','SHOVE','PUSH','PRESS','SQUEEZE','PINCH','GRIP','GRASP','CLUTCH','CLASP','HOLD','KEEP','RETAIN','MAINTAIN','PRESERVE','CONSERVE','SAVE','STORE','STASH','CACHE','DEPOSIT','PLACE','PUT','SET','LAY','REST','REPOSE','LEAN','PROP','SUPPORT','BEAR','CARRY','SHOULDER','LUG','HAUL','TOTE','PACK','LOAD','FILL','STUFF','CRAM','JAM','WEDGE','FORCE','THRUST','DRIVE','POWER','ENERGY','VIGOR','STRENGTH','MIGHT','POTENCY','FORCE','PRESSURE','TENSION','STRESS','STRAIN','LOAD','BURDEN','WEIGHT','MASS','HEAVY','LIGHT','HEAVYWEIGHT','LIGHTWEIGHT','FEATHER','DOWN','UP','ABOVE','BELOW','UNDER','OVER','THROUGH','ACROSS','ALONG','AROUND','ABOUT','NEAR','FAR','DISTANT','REMOTE','CLOSE','PROXIMATE','ADJACENT','NEIGHBOR','NEIGHBORHOOD','COMMUNITY','SOCIETY','CULTURE','CIVILIZATION','NATION','COUNTRY','STATE','PROVINCE','REGION','ZONE','AREA','DISTRICT','SECTOR','QUARTER','SECTION','DIVISION','PART','PORTION','SHARE','ALLOTMENT','RATION','QUOTA','ALLOWANCE','PERMISSION','LICENSE','PERMIT','PASS','TICKET','ADMISSION','ENTRY','ACCESS','ENTRANCE','GATE','DOOR','PORTAL','OPENING','APERTURE','VENT','HOLE','CAVITY','HOLLOW','PIT','DEPRESSION','DENT','GROOVE','FURROW','TRENCH','DITCH','CANAL','CHANNEL','PASSAGE','CORRIDOR','HALL','HALLWAY','LOBBY','FOYER','VESTIBULE','PORCH','DECK','PATIO','TERRACE','BALCONY','GALLERY','MEZZANINE','PLATFORM','STAGE','DAIS','PODIUM','PEDESTAL','BASE','FOUNDATION','GROUND','FLOOR','BOTTOM','LOW','HIGH','TOP','SUMMIT','PEAK','PINNACLE','APEX','ZENITH','CLIMAX','MAXIMUM','MINIMUM','OPTIMUM','IDEAL','PERFECT','FLAWLESS','IMPECCABLE','PRISTINE','PURE','CLEAN','CLEAR','TRANSPARENT','LUCID','OBVIOUS','EVIDENT','APPARENT','MANIFEST','PLAIN','SIMPLE','EASY','EFFORTLESS','SMOOTH','SEAMLESS','FLUID','GRACEFUL','ELEGANT','REFINED','POLISHED','CULTURED','SOPHISTICATED','URBANE','WORLDLY','EXPERIENCED','SEASONED','VETERAN','OLD','ANCIENT','ANTIQUE','VINTAGE','CLASSIC','TRADITIONAL','CONVENTIONAL','STANDARD','NORMAL','ORDINARY','COMMON','USUAL','TYPICAL','REGULAR','ROUTINE','HABITUAL','CUSTOMARY','TRADITIONAL','CEREMONIAL','RITUAL','RITES','CEREMONY','CELEBRATION','FESTIVAL','FIESTA','CARNIVAL','PARADE','PROCESSION','MARCH','DEMONSTRATION','PROTEST','RALLY','GATHERING','MEETING','ASSEMBLY','CONVENTION','CONFERENCE','SUMMIT','FORUM','SYMPOSIUM','SEMINAR','WORKSHOP','CLASS','LESSON','LECTURE','TUTORIAL','SESSION','COURSE','CURRICULUM','SYLLABUS','PROGRAM','SCHEDULE','TIMETABLE','AGENDA','CALENDAR','PLANNER','ORGANIZER','COORDINATOR','MANAGER','DIRECTOR','SUPERVISOR','OVERSEER','ADMINISTRATOR','EXECUTIVE','OFFICER','OFFICIAL','AGENT','REPRESENTATIVE','DELEGATE','ENVOY','AMBASSADOR','DIPLOMAT','NEGOTIATOR','MEDIATOR','ARBITRATOR','JUDGE','JUSTICE','MAGISTRATE','COURT','TRIBUNAL','JURY','WITNESS','TESTIMONY','EVIDENCE','PROOF','VERIFICATION','VALIDATION','CONFIRMATION','ASSURANCE','GUARANTEE','WARRANTY','PROMISE','VOW','OATH','PLEDGE','COMMITMENT','DEDICATION','DEVOTION','LOYALTY','FAITH','TRUST','BELIEF','CONVICTION','CREDENCE','CONFIDENCE','HOPE','EXPECTATION','ANTICIPATION','FORECAST','PREDICTION','PROPHECY','PROGNOSIS','DIAGNOSIS','ANALYSIS','EXAMINATION','INSPECTION','INVESTIGATION','INQUIRY','RESEARCH','STUDY','SURVEY','POLL','CENSUS','COUNT','TALLY','SCORE','TABULATION','STATISTIC','DATA','INFORMATION','FACT','DETAIL','PARTICULAR','SPECIFIC','ITEM','ELEMENT','COMPONENT','INGREDIENT','CONSTITUENT','FACTOR','ASPECT','FEATURE','CHARACTERISTIC','TRAIT','QUALITY','ATTRIBUTE','PROPERTY','NATURE','ESSENCE','SUBSTANCE','MATTER','MATERIAL','STUFF','THING','OBJECT','ENTITY','BEING','CREATURE','ANIMAL','PLANT','ORGANISM','LIFE','EXISTENCE','REALITY','TRUTH','FACT','ACTUALITY','CERTAINTY','SURETY','SECURITY','SAFETY','PROTECTION','DEFENSE','SHIELD','GUARD','WATCH','KEEP','CARE','ATTENTION','FOCUS','CONCENTRATION','EFFORT','ENERGY','POWER','FORCE','STRENGTH','VIGOR','VITALITY','LIVELINESS','SPIRIT','SOUL','MIND','BRAIN','INTELLECT','INTELLIGENCE','WISDOM','KNOWLEDGE','UNDERSTANDING','COMPREHENSION','GRASP','AWARENESS','CONSCIOUSNESS','PERCEPTION','SENSATION','FEELING','EMOTION','SENTIMENT','MOOD','TEMPER','DISPOSITION','ATTITUDE','OUTLOOK','PERSPECTIVE','VIEW','OPINION','JUDGMENT','ASSESSMENT','EVALUATION','APPRAISAL','ESTIMATE','CALCULATION','COMPUTATION','MEASUREMENT','QUANTITY','AMOUNT','NUMBER','FIGURE','SUM','TOTAL','RESULT','OUTCOME','CONSEQUENCE','EFFECT','IMPACT','INFLUENCE','POWER','AUTHORITY','CONTROL','COMMAND','ORDER','DIRECTIVE','INSTRUCTION','GUIDANCE','DIRECTION','LEADERSHIP','GUIDANCE','COUNSEL','ADVICE','RECOMMENDATION','SUGGESTION','PROPOSAL','IDEA','CONCEPT','NOTION','THOUGHT','THEORY','HYPOTHESIS','SUPPOSITION','ASSUMPTION','PRESUMPTION','BELIEF','OPINION','VIEW','PERSPECTIVE','STANDPOINT','POSITION','STANCE','POSTURE','ATTITUDE','APPROACH','METHOD','WAY','MEANS','MODE','MANNER','STYLE','FASHION','TECHNIQUE','SKILL','ABILITY','CAPACITY','CAPABILITY','COMPETENCE','PROFICIENCY','EXPERTISE','MASTERY','COMMAND','GRASP','KNOWLEDGE','UNDERSTANDING','COMPREHENSION','FAMILIARITY','ACQUAINTANCE','EXPERIENCE','PRACTICE','TRAINING','EDUCATION','LEARNING','INSTRUCTION','TEACHING','TUTORING','COACHING','MENTORING','GUIDANCE','DIRECTION','SUPERVISION','OVERSIGHT','MANAGEMENT','ADMINISTRATION','GOVERNANCE','RULE','REGULATION','LAW','STATUTE','ORDINANCE','DECREE','EDICT','MANDATE','COMMAND','ORDER','DIRECTIVE','INSTRUCTION','GUIDELINE','PRINCIPLE','RULE','STANDARD','CRITERION','MEASURE','TEST','TRIAL','EXAMINATION','ASSESSMENT','EVALUATION','JUDGMENT','VERDICT','DECISION','RULING','DETERMINATION','RESOLUTION','SOLUTION','ANSWER','RESPONSE','REPLY','REACTION','FEEDBACK','INPUT','OUTPUT','RESULT','OUTCOME','PRODUCT','CREATION','INVENTION','DISCOVERY','FINDING','DETECTION','IDENTIFICATION','RECOGNITION','REALIZATION','AWAKENING','ENLIGHTENMENT','ILLUMINATION','INSPIRATION','MOTIVATION','INCITEMENT','STIMULUS','INCENTIVE','INDUCEMENT','REWARD','PRIZE','AWARD','TROPHY','MEDAL','BADGE','HONOR','DISTINCTION','RECOGNITION','ACCLAIM','APPROVAL','ENDORSEMENT','SUPPORT','BACKING','ASSISTANCE','HELP','AID','RELIEF','SUCCOR','COMFORT','CONSOLATION','SOLACE','PEACE','TRANQUILITY','SERENITY','CALM','QUIET','SILENCE','STILL','MOTIONLESS','STATIC','STATIONARY','FIXED','STABLE','STEADY','CONSTANT','CONSISTENT','UNIFORM','REGULAR','SYSTEMATIC','ORDERLY','ORGANIZED','ARRANGED','PLANNED','PREPARED','READY','SET','GO','START','BEGIN','COMMENCE','INITIATE','LAUNCH','OPEN','INTRODUCE','PRESENT','SHOW','DISPLAY','EXHIBIT','DEMONSTRATE','PROVE','VERIFY','VALIDATE','CONFIRM','SUBSTANTIATE','CORROBORATE','SUPPORT','BACK','ENDORSE','APPROVE','SANCTION','AUTHORIZE','PERMIT','ALLOW','LET','ENABLE','EMPOWER','FACILITATE','HELP','ASSIST','AID','SERVE','CONTRIBUTE','PARTICIPATE','ENGAGE','INVOLVE','INCLUDE','EMBRACE','ACCEPT','RECEIVE','WELCOME','GREET','SALUTE','ACKNOWLEDGE','RECOGNIZE','IDENTIFY','DISTINGUISH','DIFFERENTIATE','DISCRIMINATE','SEPARATE','DIVIDE','SPLIT','PART','SEVER','CUT','SLICE','CHOP','HEW','CARVE','ENGRAVE','ETCH','INSCRIBE','WRITE','PRINT','PUBLISH','ISSUE','RELEASE','DISSEMINATE','DISTRIBUTE','CIRCULATE','SPREAD','SCATTER','DISPERSE','DISSEMINATE','BROADCAST','TRANSMIT','SEND','CONVEY','COMMUNICATE','EXPRESS','ARTICULATE','UTTER','SPEAK','TALK','CONVERSE','DISCUSS','DEBATE','ARGUE','DISPUTE','CONTEND','COMPETE','RIVAL','CHALLENGE','CONFRONT','FACE','MEET','ENCOUNTER','EXPERIENCE','UNDERGO','ENDURE','SUFFER','TOLERATE','BEAR','WITHSTAND','RESIST','OPPOSE','DEFY','REBEL','REVOLT','RISE','REVOLUTION','UPRISING','INSURRECTION','REBELLION','RESISTANCE','OPPOSITION','DEFIANCE','PROTEST','OBJECTION','COMPLAINT','GRIEVANCE','DISCONTENT','DISSATISFACTION','DISAPPROVAL','DISLIKE','AVERSION','ANTIPATHY','HOSTILITY','ENMITY','HATRED','LOATHING','ABHORRENCE','DETESTATION','DISGUST','REPVLSION','NAUSEA','SICKNESS','ILLNESS','DISEASE','MALADY','AILMENT','DISORDER','AFFLICTION','CONDITION','STATE','SITUATION','CIRCUMSTANCE','CONTEXT','SETTING','ENVIRONMENT','SURROUNDINGS','AMBIENCE','ATMOSPHERE','CLIMATE','WEATHER','SEASON','TIME','PERIOD','ERA','EPOCH','AGE','GENERATION','COHORT','GROUP','CLASS','CATEGORY','TYPE','KIND','SORT','VARIETY','SPECIES','BREED','STRAIN','RACE','LINEAGE','ANCESTRY','HERITAGE','LEGACY','INHERITANCE','BIRTHRIGHT','PATRIMONY','MATRIMONY','MARRIAGE','WEDLOCK','UNION','PARTNERSHIP','ALLIANCE','COALITION','FEDERATION','CONFEDERATION','LEAGUE','ASSOCIATION','ORGANIZATION','INSTITUTION','ESTABLISHMENT','FOUNDATION','CORPORATION','COMPANY','FIRM','BUSINESS','ENTERPRISE','VENTURE','UNDERTAKING','ENDEAVOR','EFFORT','ATTEMPT','TRY','TRIAL','TEST','EXPERIMENT','EXPERIENCE','ADVENTURE','EXPLOIT','FEAT','ACHIEVEMENT','ACCOMPLISHMENT','ATTAINMENT','SUCCESS','VICTORY','TRIUMPH','WIN','CONQUEST','DEFEAT','LOSS','FAILURE','MISHAP','ACCIDENT','INCIDENT','EVENT','OCCURRENCE','HAPPENING','EPISODE','EPIC','SAGA','LEGEND','MYTH','FABLE','PARABLE','ALLEGORY','METAPHOR','SIMILE','ANALOGY','COMPARISON','PARALLEL','EQUIVALENT','COUNTERPART','MATCH','COUNTER','OPPOSITE','REVERSE','INVERSE','CONVERSE','CONTRARY','CONTRAST','DIFFERENCE','DISTINCTION','DISCREPANCY','DIVERGENCE','VARIATION','DEVIATION','CHANGE','ALTERATION','MODIFICATION','ADJUSTMENT','ADAPTATION','ACCOMMODATION','CONFORMITY','COMPLIANCE','OBEDIENCE','SUBMISSION','YIELDING','SURRENDER','CAPITULATION','DEFEAT','CONCESSION','COMPROMISE','SETTLEMENT','AGREEMENT','ACCORD','CONCORD','HARMONY','UNISON','UNITY','SOLIDARITY','COHESION','COOPERATION','COLLABORATION','TEAMWORK','PARTNERSHIP','ALLIANCE','ASSOCIATION','AFFILIATION','CONNECTION','RELATION','RELATIONSHIP','LINK','TIE','BOND','ATTACHMENT','AFFINITY','RAPPORT','CAMARADERIE','COMPANIONSHIP','FRIENDSHIP','FELLOWSHIP','BROTHERHOOD','SISTERHOOD','KINSHIP','FAMILY','RELATIVE','KIN','KINDRED','CLAN','TRIBE','HOUSE','DYNASTY','LINE','LINEAGE','GENEALOGY','PEDIGREE','ANCESTRY','DESCENT','ORIGIN','SOURCE','ROOT','BEGINNING','START','COMMENCEMENT','INAUGURATION','LAUNCH','DEBUT','PREMIERE','FIRST','INITIAL','OPENING','INTRODUCTORY','PRELIMINARY','PRIMARY','PRINCIPAL','CHIEF','MAIN','CENTRAL','KEY','CRITICAL','CRUCIAL','ESSENTIAL','VITAL','IMPORTANT','SIGNIFICANT','MEANINGFUL','CONSEQUENTIAL','MOMENTOUS','WEIGHTY','SERIOUS','GRAVE','SEVERE','HARSH','STERN','STRICT','RIGOROUS','STRINGENT','TOUGH','HARD','DIFFICULT','CHALLENGING','DEMANDING','EXACTING','ARDUOUS','LABORIOUS','STRENUOUS','TIRING','EXHAUSTING','FATIGUING','WEARING','DRAINING','DEPLETING','CONSUMING','EXPENDING','USING','UTILIZING','EMPLOYING','APPLYING','PRACTICING','EXERCISING','PERFORMING','EXECUTING','CARRYING','CONDUCTING','MANAGING','DIRECTING','SUPERVISING','OVERSEEING','ADMINISTERING','GOVERNING','RULING','REIGNING','CONTROLLING','COMMANDING','LEADING','GUIDING','STEERING','NAVIGATING','PILOTING','DRIVING','OPERATING','RUNNING','WORKING','FUNCTIONING','ACTING','BEHAVING','CONDUCTING','COMPORTING','DEMEANING','CARRYING','BEARING','SUSTAINING','SUPPORTING','UPHOLDING','MAINTAINING','PRESERVING','CONSERVING','PROTECTING','DEFENDING','GUARDING','SHIELDING','SCREENING','COVERING','WRAPPING','ENCLOSING','SURROUNDING','ENCIRCLING','ENCOMPASSING','EMBRACING','HUGGING','CLASPING','GRASPING','HOLDING','GRIPPING','CLUTCHING','CLINGING','ADHERING','STICKING','ATTACHING','FASTENING','SECURING','BINDING','TYING','KNOTTING','LACING','BUTTONING','ZIPPERING','SNAPPING','HOOKING','LOCKING','BOLTING','LATCHING','CLOSING','SHUTTING','SEALING','PLUGGING','STOPPING','BLOCKING','OBSTRUCTING','BARRING','BANNING','PROHIBITING','FORBIDDING','PREVENTING','DETERRING','DISCOURAGING','DISSUADING','ADMONISHING','WARNING','CAUTIONING','ALERTING','NOTIFYING','INFORMING','TELLING','RELATING','RECOUNTING','NARRATING','RECORDING','DOCUMENTING','REGISTERING','LOGGING','LISTING','CATALOGING','INDEXING','FILE','FOLDER','DOCUMENT','PAPER','RECORD','REPORT','STATEMENT','DECLARATION','ANNOUNCEMENT','PROCLAMATION','NOTICE','BULLETIN','NEWS','INFORMATION','INTELLIGENCE','DATA','FACTS','DETAILS','PARTICULARS','SPECIFICS','ITEMS','ENTRIES','ELEMENTS','COMPONENTS','PARTS','PIECES','SEGMENTS','SECTIONS','DIVISIONS','PORTIONS','FRACTIONS','FRAGMENTS','BITS','SCRAPS','SHREDS','REMNANTS','REMAINS','RESIDUE','LEFTOVERS','WASTE','REFUSE','GARBAGE','TRASH','RUBBISH','LITTER','DEBRIS','JUNK','CLUTTER','MESS','DISORDER','CHAOS','ANARCHY','LAWLESSNESS','CRIME','SIN','VICE','WRONGDOING','MISDEED','OFFENSE','VIOLATION','INFRINGEMENT','BREACH','TRESPASS','TRANSGRESSION','FAULT','ERROR','MISTAKE','BLUNDER','MISSTEP','SLIP','LAPSE','OMISSION','OVERSIGHT','NEGLECT','CARELESSNESS','RECKLESSNESS','IMPRUDENCE','INDISCRETION','FOLLY','FOOLISHNESS','STUPIDITY','IGNORANCE','UNKNOWLEDGE','NAIVETE','INNOCENCE','PURITY','CLEANLINESS','HYGIENE','SANITATION','HEALTH','WELLNESS','FITNESS','VIGOR','VITALITY','ENERGY','POWER','STRENGTH','FORCE','MIGHT','POTENCY','EFFICACY','EFFECTIVENESS','SUCCESS','PROSPERITY','FORTUNE','LUCK','CHANCE','FATE','DESTINY','DOOM','LOT','PORTION','SHARE','PART','ROLE','FUNCTION','PURPOSE','OBJECTIVE','GOAL','AIM','TARGET','END','MEANS','METHOD','WAY','APPROACH','STRATEGY','TACTIC','PLAN','SCHEME','DESIGN','PLOT','CONSPIRACY','INTRIGUE','MANEUVER','MOVE','ACTION','ACT','DEED','PERFORMANCE','EXECUTION','IMPLEMENTATION','APPLICATION','PRACTICE','EXERCISE','DRILL','TRAINING','PREPARATION','REHEARSAL','PRACTICE','SESSION','LESSON','CLASS','COURSE','CURRICULUM','PROGRAM','SYLLABUS','SCHEDULE','TIMETABLE','AGENDA','CALENDAR','PLAN','BLUEPRINT','OUTLINE','SKETCH','DRAFT','PRELIMINARY','TENTATIVE','PROVISIONAL','TEMPORARY','TRANSIENT','FLEETING','BRIEF','SHORT','QUICK','FAST','RAPID','SWIFT','SPEEDY','EXPEDITIOUS','PROMPT','IMMEDIATE','INSTANT','SUDDEN','ABRUPT','SHARP','KEEN','ACUTE','PENETRATING','PIERCING','STABBING','CUTTING','SLICING','SLASHING','CHOPPING','HEWING','CARVING','ENGRAVING','ETCHING','INSCRIBING','WRITING','PRINTING','PUBLISHING','ISSUING','RELEASING','DISSEMINATING','DISTRIBUTING','CIRCULATING','SPREADING','SCATTERING','DISPERSING','BROADCASTING','TRANSMITTING','SENDING','CONVEYING','COMMUNICATING','EXPRESSING','ARTICULATING','UTTERING','SPEAKING','TALKING','CONVERSING','DISCUSSING','DEBATING','ARGUING','DISPUTING','CONTENDING','COMPETING','RIVALING','CHALLENGING','CONFRONTING','FACING','MEETING','ENCOUNTERING','EXPERIENCING','UNDERGOING','ENDURING','SUFFERING','TOLERATING','BEARING','WITHSTANDING','RESISTING','OPPOSING','DEFYING','REBELLING','REVOLTING','RISING'
];

// Filter to only words that can fit on our board (3-8 letters typically)
const VALID_WORDS = WORD_POOL.filter(w => w.length >= 3 && w.length <= 8);

// Directions: [rowDelta, colDelta]
const DIRECTIONS = [
  [0, 1],   // horizontal right
  [1, 0],   // vertical down
  [1, 1],   // diagonal down-right
  [-1, 1],  // diagonal up-right
  [0, -1],  // horizontal left
  [-1, 0],  // vertical up
  [-1, -1], // diagonal up-left
  [1, -1],  // diagonal down-left
];

export function pickTargetWords(count, minLength = 3, maxLength = 8) {
  const filtered = VALID_WORDS.filter(w => w.length >= minLength && w.length <= maxLength);
  const shuffled = [...filtered].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

export function canPlaceWord(board, word, startRow, startCol, direction) {
  const [dRow, dCol] = direction;
  const size = board.length;
  
  for (let i = 0; i < word.length; i++) {
    const row = startRow + i * dRow;
    const col = startCol + i * dCol;
    
    // Out of bounds
    if (row < 0 || row >= size || col < 0 || col >= size) {
      return false;
    }
    
    // Cell must be empty or match the letter
    if (board[row][col] !== null && board[row][col] !== word[i]) {
      return false;
    }
  }
  
  return true;
}

export function placeWord(board, word, startRow, startCol, direction) {
  const [dRow, dCol] = direction;
  const placed = [];
  
  for (let i = 0; i < word.length; i++) {
    const row = startRow + i * dRow;
    const col = startCol + i * dCol;
    board[row][col] = word[i];
    placed.push({ row, col, letter: word[i] });
  }
  
  return placed;
}

export function generateBoardWithWords(boardSize, targetWordCount = 20) {
  // Initialize empty board
  const board = Array(boardSize).fill(null).map(() => Array(boardSize).fill(null));
  const placedWords = [];
  
  // Sort words by length (longer first - harder to place)
  const words = pickTargetWords(targetWordCount * 2, 3, 8).sort((a, b) => b.length - a.length);
  
  // Try to place words
  for (const word of words) {
    if (placedWords.length >= targetWordCount) break;
    
    let placed = false;
    const attempts = 50;
    
    for (let attempt = 0; attempt < attempts && !placed; attempt++) {
      const startRow = Math.floor(Math.random() * boardSize);
      const startCol = Math.floor(Math.random() * boardSize);
      
      // Shuffle directions for variety
      const shuffledDirections = [...DIRECTIONS].sort(() => Math.random() - 0.5);
      
      for (const direction of shuffledDirections) {
        if (canPlaceWord(board, word, startRow, startCol, direction)) {
          placeWord(board, word, startRow, startCol, direction);
          placedWords.push({
            word,
            startRow,
            startCol,
            direction,
          });
          placed = true;
          break;
        }
      }
    }
  }
  
  // Fill empty cells with random letters
  const vowels = 'AEIOU';
  const consonants = 'BCDFGHJKLMNPQRSTVWXYZ';
  
  for (let row = 0; row < boardSize; row++) {
    for (let col = 0; col < boardSize; col++) {
      if (board[row][col] === null) {
        // 40% vowel, 60% consonant for natural distribution
        board[row][col] = Math.random() < 0.4 
          ? vowels[Math.floor(Math.random() * vowels.length)]
          : consonants[Math.floor(Math.random() * consonants.length)];
      }
    }
  }
  
  return { board, placedWords };
}

// Get 5 visible target words from the full list
export function getVisibleTargetWords(allWords, foundWords, visibleCount = 5) {
  const remaining = allWords.filter(w => !foundWords.includes(w.word));
  return remaining.slice(0, visibleCount);
}

// Check if a word matches any target word
export function isTargetWord(word, targetWords) {
  return targetWords.some(t => t.word === word);
}