const LETTER_FREQ = { A: 9, B: 2, C: 2, D: 4, E: 12, F: 2, G: 3, H: 2, I: 9, J: 1, K: 1, L: 4, M: 2, N: 6, O: 8, P: 2, Q: 1, R: 6, S: 4, T: 6, U: 4, V: 2, W: 2, X: 1, Y: 2, Z: 1 };
const VOWELS = ['A', 'E', 'I', 'O', 'U'];
const CONSONANTS = Object.keys(LETTER_FREQ).filter(l => !VOWELS.includes(l));
const SPECIAL_TILES = ['gold-bean', 'diamond', 'dexter', 'frog', 'microphone', 'texas-flag'];

function shuffle(array) {
  const newArray = [...array];
  for (let i = newArray.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [newArray[i], newArray[j]] = [newArray[j], newArray[i]];
  }
  return newArray;
}

export function generateLetterBoard(boardSize, specialTilesEnabled = true, outlawChance = 0.08) {
  const totalCells = boardSize * boardSize;
  const targetVowels = Math.floor(totalCells * 0.35);
  const targetConsonants = totalCells - targetVowels;
  
  let letters = [];
  Object.entries(LETTER_FREQ).forEach(([letter, count]) => {
    for (let i = 0; i < count; i++) letters.push(letter);
  });
  letters = shuffle(letters);
  
  let vowels = letters.filter(l => VOWELS.includes(l)).slice(0, targetVowels);
  let consonants = letters.filter(l => !VOWELS.includes(l)).slice(0, targetConsonants);
  
  while (vowels.length < targetVowels) vowels.push(VOWELS[Math.floor(Math.random() * VOWELS.length)]);
  while (consonants.length < targetConsonants) consonants.push(CONSONANTS[Math.floor(Math.random() * CONSONANTS.length)]);
  
  const allLetters = shuffle([...vowels, ...consonants]);
  const board = [];
  
  let letterIndex = 0;
  for (let row = 0; row < boardSize; row++) {
    const boardRow = [];
    for (let col = 0; col < boardSize; col++) {
      const letter = allLetters[letterIndex++];
      let specialType = null;
      let isOutlaw = false;
      
      if (Math.random() < outlawChance) {
        isOutlaw = true;
      } else if (specialTilesEnabled && Math.random() < 0.12) {
        specialType = SPECIAL_TILES[Math.floor(Math.random() * SPECIAL_TILES.length)];
      }
      
      boardRow.push({ letter, specialType, isOutlaw });
    }
    board.push(boardRow);
  }
  
  return board;
}

export function getAdjacentCells(row, col, boardSize) {
  const adjacent = [];
  for (let dr = -1; dr <= 1; dr++) {
    for (let dc = -1; dc <= 1; dc++) {
      if (dr === 0 && dc === 0) continue;
      const newRow = row + dr;
      const newCol = col + dc;
      if (newRow >= 0 && newRow < boardSize && newCol >= 0 && newCol < boardSize) {
        adjacent.push({ row: newRow, col: newCol });
      }
    }
  }
  return adjacent;
}

export function calculateScore(wordLength, selectedCells, board) {
  const baseScores = { 3: 10, 4: 20, 5: 35, 6: 50, 7: 75, 8: 100 };
  let score = baseScores[Math.min(wordLength, 8)] || 100;
  let hasMicrophone = false;
  
  selectedCells.forEach(cell => {
    const tile = board[cell.row][cell.col];
    if (tile.specialType === 'gold-bean') score += 50;
    if (tile.specialType === 'diamond') score += 100;
    if (tile.specialType === 'microphone') hasMicrophone = true;
    if (tile.specialType === 'dexter') score += 75;
    if (tile.isOutlaw) score += 150;
  });
  
  if (hasMicrophone) score *= 2;
  if (wordLength >= 7) score += 25;
  if (wordLength >= 8) score += 50;
  
  return score;
}

const COMMON_WORDS = new Set(['THE','AND','FOR','ARE','BUT','NOT','YOU','ALL','ANY','CAN','HAD','HAS','HIM','HIS','HOW','MAN','NEW','NOW','OLD','SEE','TWO','WAY','WHO','BOY','DID','ITS','LET','PUT','SAY','SHE','TOO','USE','DAD','MOM','CAT','DOG','BAT','HAT','MAT','RAT','SAT','FAT','EAT','ATE','EAR','EYE','ARM','LEG','FOOT','HAND','FACE','HAIR','SKIN','BONE','BLOOD','HEART','LUNG','LIVER','BRAIN','NERVE','MUSCLE','JOINT','FINGER','TOES','NAIL','TEETH','NOSE','MOUTH','LIPS','TONGUE','THROAT','CHEST','WAIST','HIPS','KNEE','ANKLE','BACK','NECK','HEAD','BODY','SOUL','MIND','SPIRIT','LOVE','HATE','LIKE','WISH','HOPE','DREAM','PLAN','IDEA','WORD','GAME','PLAY','TIME','YEAR','DAYS','WEEK','MONTH','HOUR','MINUTE','SECOND','MOMENT','SEASON','SPRING','SUMMER','FALL','WINTER','SUN','MOON','STAR','SKY','CLOUD','RAIN','SNOW','WIND','STORM','FIRE','WATER','EARTH','TREE','FLOWER','GRASS','LEAF','ROOT','BRANCH','FRUIT','SEED','BIRD','FISH','ANIMAL','PET','WILD','LION','TIGER','BEAR','WOLF','FOX','DEER','HORSE','COW','PIG','SHEEP','GOAT','CHICKEN','DUCK','GOOSE','TURKEY','EAGLE','HAWK','OWL','CROW','ROBIN','BLUE','RED','GREEN','YELLOW','ORANGE','PURPLE','PINK','BROWN','BLACK','WHITE','GRAY','GOLD','SILVER','BRONZE','IRON','STEEL','COPPER','BRASS','LEAD','ZINC','TIN','PLASTIC','RUBBER','GLASS','WOOD','PAPER','CLOTH','FABRIC','THREAD','STRING','ROPE','CHAIN','WIRE','CABLE','TUBE','PIPE','WHEEL','AXLE','GEAR','LEVER','PULLEY','SPRING','MOTOR','ENGINE','MACHINE','TOOL','DEVICE','GADGET','WIDGET','GIZMO','INVENTION','DISCOVERY','CREATION','PRODUCT','ITEM','THING','OBJECT','SUBSTANCE','MATERIAL','ELEMENT','COMPOUND','MIXTURE','SOLUTION','LIQUID','SOLID','GAS','VAPOR','STEAM','SMOKE','DUST','DIRT','SAND','ROCK','STONE','PEBBLE','BOULDER','MOUNTAIN','HILL','VALLEY','PLAIN','DESERT','FOREST','JUNGLE','SWAMP','MARSH','BOG','FEN','MOOR','PRAIRIE','MEADOW','FIELD','PASTURE','FARM','RANCH','GARDEN','PARK','YARD','LAWN','PATH','ROAD','STREET','AVENUE','BOULEVARD','DRIVE','LANE','COURT','PLACE','WAY','CIRCLE','SQUARE','PLAZA','HIGHWAY','FREEWAY','BRIDGE','TUNNEL','OVERPASS','UNDERPASS','INTERSECTION','JUNCTION','CROSSING','CORNER','BEND','CURVE','SLOPE','GRADE','INCLINE','DECLINE','ASCENT','DESCENT','RISE','FALL','DROP','CLIFF','EDGE','BRINK','VERGE','MARGIN','BORDER','BOUNDARY','LIMIT','FRONTIER','OUTSKIRTS','PERIPHERY','CIRCUMFERENCE','PERIMETER','DIAMETER','RADIUS','CENTER','MIDDLE','CORE','HEART','NUCLEUS','ESSENCE','SUBSTANCE','NATURE','CHARACTER','QUALITY','PROPERTY','ATTRIBUTE','FEATURE','TRAIT','CHARACTERISTIC','ASPECT','ELEMENT','FACTOR','COMPONENT','PART','PIECE','BIT','FRAGMENT','SHARD','SLIVER','SPLINTER','CHIP','SCRAP','REMNANT','REMAINDER','RESIDUE','LEFTOVER','WASTE','TRASH','GARBAGE','RUBBISH','LITTER','DEBRIS','JUNK','CLUTTER','MESS','DIRT','GRIME','FILTH','SOIL','STAIN','SPOT','BLOTCH','SPECK','DOT','POINT','MARK','LINE','STROKE','DASH','SCRATCH','SCUFF','SCRAPE','CUT','SLICE','SLIT','GASH','WOUND','INJURY','HARM','DAMAGE','HURT','PAIN','ACHE','SORE','THROB','STING','SMART','BURN','ITCH','TINGLE','NUMB','PRICKLE','CRAWL','CREEP','SLITHER','SLIDE','SLIP','SKID','SKATE','GLIDE','COAST','DRIFT','FLOAT','SWIM','WADE','DIVE','PLUNGE','SINK','DROP','FALL','TUMBLE','TOPPLE','TRIP','STUMBLE','JUMP','LEAP','HOP','SKIP','STEP','WALK','MARCH','STROLL','STRIDE','STRUT','SAUNTER','AMBLE','SHUFFLE','TRUDGE','PLOD','TREK','HIKE','CLIMB','ASCEND','RISE','MOUNT','SCALE','SURMOUNT','TOP','REACH','ATTAIN','ACHIEVE','GAIN','EARN','WIN','SECURE','OBTAIN','ACQUIRE','GET','PROCURE','FETCH','BRING','CARRY','CONVEY','TRANSPORT','TRANSFER','MOVE','SHIFT','RELOCATE','DISPLACE','REMOVE','DELETE','ERASE','CANCEL','VOID','NULLIFY','ANNUL','REVOKE','RESCIND','REPEAL','ABOLISH','ELIMINATE','ERADICATE','EXTERMINATE','DESTROY','DEMOLISH','RAZE','WRECK','RUIN','DEVASTATE','RAVAGE','PILLAGE','PLUNDER','LOOT','SACK','RAID','ATTACK','ASSAULT','STRIKE','HIT','SMASH','CRASH','BANG','SLAM','THUMP','THUD','BUMP','KNOCK','TAP','PAT','POKE','PROD','NUDGE','SHOVE','PUSH','PRESS','SQUEEZE','PINCH','GRIP','GRASP','CLUTCH','CLASP','HOLD','KEEP','RETAIN','MAINTAIN','PRESERVE','CONSERVE','SAVE','STORE','STASH','CACHE','DEPOSIT','PLACE','PUT','SET','LAY','REST','REPOSE','LEAN','PROP','SUPPORT','BEAR','CARRY','SHOULDER','LUG','HAUL','TOTE','PACK','LOAD','FILL','STUFF','CRAM','JAM','WEDGE','SQUEEZE','FORCE','THRUST','SHOVE','PUSH','PRESS','BEAR','WEIGH','LOAD','BURDEN','TAX','STRAIN','STRESS','PRESSURE','TENSION','FORCE','POWER','ENERGY','VIGOR','STRENGTH','MIGHT','POTENCY','EFFECTIVENESS','EFFICACY','IMPACT','INFLUENCE','EFFECT','RESULT','OUTCOME','CONSEQUENCE','AFTERMATH','FALLOUT','REPERCUSSION','RAMIFICATION','IMPLICATION','SIGNIFICANCE','IMPORT','MEANING','SENSE','PURPORT','SUBSTANCE','ESSENCE','GIST','POINT','CRUX','HEART','CORE','NUCLEUS','CENTER','FOCUS','HUB','NEXUS','NODE','JUNCTION','CONNECTION','LINK','TIE','BOND','ATTACHMENT','AFFINITY','RELATIONSHIP','ASSOCIATION','AFFILIATION','ALLIANCE','PARTNERSHIP','COLLABORATION','COOPERATION','TEAMWORK','SYNERGY','UNITY','SOLIDARITY','HARMONY','ACCORD','AGREEMENT','CONCORD','CONSENT','CONCURRENCE','CONSENSUS','UNANIMITY','ACQUIESCENCE','COMPLIANCE','CONFORMITY','ADHERENCE','OBSERVANCE','FOLLOWING','OBEDIENCE','SUBMISSION','YIELDING','SURRENDER','CAPITULATION','DEFEAT','LOSS','FAILURE','MISHAP','MISFORTUNE','BAD','LUCK','CHANCE','FATE','DESTINY','DOOM','LOT','PORTION','SHARE','PART','PIECE','SECTION','SEGMENT','DIVISION','PARTITION','SEPARATION','ISOLATION','SEGREGATION','DETACHMENT','DISCONNECTION','DISJUNCTION','SEVERANCE','RUPTURE','BREAK','FRACTURE','CRACK','SPLIT','RIFT','FISSURE','CREVICE','GAP','OPENING','APERTURE','HOLE','CAVITY','VOID','EMPTY','SPACE','VACUUM','NEGATION','ABSENCE','LACK','WANT','NEED','REQUIREMENT','NECESSITY','ESSENTIAL','PREREQUISITE','DEMAND','REQUEST','PLEA','APPEAL','PETITION','SOLICITATION','INVITATION','OFFER','PROPOSAL','SUGGESTION','RECOMMENDATION','ADVICE','COUNSEL','GUIDANCE','DIRECTION','INSTRUCTION','TEACHING','LESSON','TUTORIAL','TRAINING','EDUCATION','LEARNING','STUDY','RESEARCH','INVESTIGATION','EXPLORATION','EXAMINATION','ANALYSIS','EVALUATION','ASSESSMENT','APPRAISAL','JUDGMENT','OPINION','VIEW','PERSPECTIVE','STANDPOINT','ANGLE','ASPECT','SIDE','FACE','SURFACE','EXTERIOR','OUTSIDE','INTERIOR','INSIDE','WITHIN','INTERNAL','INTRINSIC','INHERENT','INNATE','NATURAL','INSTINCTIVE','INTUITIVE','SPONTANEOUS','AUTOMATIC','MECHANICAL','ROUTINE','HABITUAL','CUSTOMARY','TRADITIONAL','CONVENTIONAL','ORTHODOX','STANDARD','NORMAL','TYPICAL','USUAL','COMMON','ORDINARY','AVERAGE','MEDIUM','MODERATE','MIDDLE','MEAN','INTERMEDIATE','INTERVENING','INTERPOSING','INTERCEDING','MEDIATING','ARBITRATING','NEGOTIATING','BARGAINING','DEALING','TRADING','EXCHANGING','SWAPPING','SUBSTITUTING','REPLACING','SUPPLANTING','SUPERS','PLAY','GAME','WORD','WRANGLER','TEXAS','NOMAD','GAMES','ROOM','CODE','PLAYER','SCORE','POINT','BOARD','LETTER','CELL','SELECT','SUBMIT','CLEAR','TIMER','ROUND','STATUS','ACTIVE','WAITING','FINISHED','WINNER','LOSER','SINGLE','MULTI','TEAM','BATTLE','MODE','DIFFICULTY','SIMPLETON','READER','SCHOLAR','GRID','SIZE','SPECIAL','TILE','GOLD','BEAN','DIAMOND','DEXTER','FROG','MICROPHONE','FLAG','BONUS','PENALTY','EVENT','STEAL','DOUBLE','ADJACENT','HORIZONTAL','VERTICAL','DIAGONAL','MINIMUM','LENGTH','VALID','DICTIONARY','DUPLICATE','FOUND','ALREADY','USED','ONCE','PER','THREE','FOUR','FIVE','SIX','SEVEN','EIGHT','NINE','TEN','PLUS','POINTS','BASE','TOTAL','FINAL','STANDINGS','LEADERBOARD','RANK','POSITION','SEAT','NUMBER','NAME','INPUT','JOIN','CREATE','HOST','SCREEN','CONNECTED','DISCONNECTED','ERROR','LOADING','SETUP','PLAYING','OVER','REVEAL','ANSWER','CORRECT','WRONG','STRIKE','TURN','CURRENT','NEXT','PREVIOUS','FIRST','LAST','INITIAL','START','END','BEGIN','FINISH','COMPLETE','WHOLE','PART','FULL','EMPTY','TRUE','FALSE','YES','NO','OK','CANCEL','CONFIRM','REJECT','ENABLE','DISABLE','SHOW','HIDE','VISIBLE','INVISIBLE','PUBLIC','PRIVATE','SHARED','UNIQUE','COMMON','RARE','LEGENDARY','EPIC','MYTHIC','ABNORMAL','NATURAL','ARTIFICIAL','REAL','FAKE','GENUINE','AUTHENTIC','ORIGINAL','COPY','CREATIVE','IMAGINATIVE','INNOVATIVE','TRADITIONAL','MODERN','ANCIENT','CONTEMPORARY','HISTORICAL','FUTURE','PAST','PRESENT','CURRENT','FORMER','LATTER','RECENT','DISTANT','IMMEDIATE','INSTANT','DELAYED','POSTPONED','CANCELLED','SCHEDULED','PLANNED','EXPECTED','UNEXPECTED','SURPRISING','SHOCKING','AMAZING','ASTONISHING','ASTOUNDING','WONDERFUL','MARVELOUS','FANTASTIC','TERRIFIC','EXCELLENT','SUPERIOR','INFERIOR','PERFECT','IMPERFECT','FLAWLESS','FLAWED','ENTIRE','FRAGMENTED','UNIFIED','DIVIDED','CONNECTED','DISCONNECTED','LINKED','UNLINKED','RELATED','UNRELATED','ASSOCIATED','ATTACHED','DETACHED','BOUND','UNBOUND','TIED','UNTIED','FASTENED','UNFASTENED','SECURED','UNSECURED','FIXED','UNFIXED','STABLE','UNSTABLE','STEADY','UNSTEADY','BALANCED','UNBALANCED','EVEN','UNEVEN','LEVEL','UNLEVEL','FLAT','CURVED','STRAIGHT','DIRECT','INDIRECT','UPRIGHT','INCLINED','VERTICAL','HORIZONTAL','DIAGONAL','PERPENDICULAR','PARALLEL','CONVERGING','DIVERGING','INTERSECTING','CROSSING','MEETING','SEPARATING','JOINING','UNITING','DIVIDING','SPLITTING','BREAKING','MENDING','REPAIRING','FIXING','DESTROYING','CREATING','BUILDING','DEMOLISHING','CONSTRUCTING','ASSEMBLING','DISASSEMBLING','MAKING','UNMAKING','PRODUCING','CONSUMING','GENERATING','DEPLETING','INCREASING','DECREASING','GROWING','SHRINKING','EXPANDING','CONTRACTING','ENLARGING','REDUCING','AMPLIFYING','DIMINISHING','STRENGTHENING','WEAKENING','IMPROVING','WORSENING','BETTERING','DETERIORATING','ADVANCING','RETREATING','PROGRESSING','REGRESSING','DEVELOPING','EVOLVING','TRANSFORMING','CHANGING','STATIC','DYNAMIC','ACTIVE','PASSIVE','ENERGETIC','LETHARGIC','VIGOROUS','WEAK','POWERFUL','POWERLESS','MIGHTY','FEEBLE','POTENT','IMPOTENT','POSITIVE','NEGATIVE','CONSTRUCTIVE','DESTRUCTIVE','HELPFUL','UNHELPFUL','USEFUL','USELESS','VALUABLE','VALUELESS','WORTHWHILE','WORTHLESS','MEANINGFUL','MEANINGLESS','SIGNIFICANT','INSIGNIFICANT','IMPORTANT','UNIMPORTANT','RELEVANT','IRRELEVANT','MATERIAL','IMMATERIAL','ESSENTIAL','NONESSENTIAL','NECESSARY','UNNECESSARY','REQUIRED','OPTIONAL','MANDATORY','VOLUNTARY','COMPULSORY','DISCRETIONARY','AUTOMATIC','MANUAL','MECHANICAL','ELECTRONIC','DIGITAL','ANALOG','VIRTUAL','PHYSICAL','REAL','IMAGINARY','ACTUAL','THEORETICAL','PRACTICAL','APPLIED','PURE','SIMPLE','COMPLEX','COMPLICATED','EASY','DIFFICULT','HARD','SOFT','TOUGH','TENDER','GENTLE','HARSH','MILD','SEVERE','EXTREME','MODERATE','RADICAL','CONSERVATIVE','LIBERAL','PROGRESSIVE','REACTIONARY','REVOLUTIONARY','REFORMIST','TRADITIONALIST','MODERNIST','CLASSIC','ROMANTIC','REALISTIC','IDEALISTIC','PRAGMATIC','DOGMATIC','FLEXIBLE','RIGID','ADAPTABLE','UNADAPTABLE','VERSATILE','LIMITED','UNLIMITED','FINITE','INFINITE','ENDLESS','TERMINAL','FINAL','INITIAL','FIRST','LAST','PRIMARY','SECONDARY','TERTIARY','MAJOR','MINOR','PRINCIPAL','SUBORDINATE','CHIEF','ASSISTANT','HEAD','TAIL','TOP','BOTTOM','FRONT','BACK','SIDE','CENTER','EDGE','MIDDLE','OUTER','INNER','UPPER','LOWER','HIGHER','SUPERIOR','INFERIOR','SENIOR','JUNIOR','ELDER','YOUNGER','OLDER','NEWER','EARLIER','LATER','FORMER','LATTER','PRECEDING','FOLLOWING','LEADING','TRAILING','WINNING','LOSING','VICTORIOUS','DEFEATED','TRIUMPHANT','FAILED','ACHIEVED','UNACHIEVED','ACCOMPLISHED','UNACCOMPLISHED','ATTAINED','UNATTAINED','REALIZED','UNREALIZED','FULFILLED','UNFULFILLED','COMPLETED','UNCOMPLETED','FINISHED','UNFINISHED','DONE','UNDO','STARTED','ENDED','BEGUN','CONCLUDED','OPENED','CLOSED','LAUNCHED','TERMINATED','INITIATED','ABORTED','COMMENCED','CEASED','RESUMED','PAUSED','CONTINUED','INTERRUPTED','SUSTAINED','BROKEN','MAINTAINED','ABANDONED','PRESERVED','CONSERVED','SAVED','LOST','FOUND','DISCOVERED','HIDDEN','REVEALED','CONCEALED','EXPOSED','COVERED','UNCOVERED','PROTECTED','UNPROTECTED','DEFENDED','ATTACKED','SECURED','THREATENED','SAFE','DANGEROUS','RISKY','CAUTIOUS','RECKLESS','CAREFUL','CARELESS','ATTENTIVE','INATTENTIVE','ALERT','OBLIVIOUS','AWARE','UNAWARE','CONSCIOUS','UNCONSCIOUS','KNOWING','IGNORANT','INFORMED','UNINFORMED','EDUCATED','UNEDUCATED','LEARNED','UNLEARNED','SCHOLARLY','ACADEMIC','INTELLECTUAL','INTELLIGENT','UNINTELLIGENT','SMART','DUMB','BRIGHT','DIM','BRILLIANT','DULL','GENIUS','IDIOT','TALENTED','GIFTED','SKILLED','UNSKILLED','TRAINED','UNTRAINED','EXPERIENCED','INEXPERIENCED','EXPERT','NOVICE','PROFESSIONAL','AMATEUR','QUALIFIED','UNQUALIFIED','CERTIFIED','UNCERTIFIED','LICENSED','UNLICENSED','ACCREDITED','UNACCREDITED','APPROVED','UNAPPROVED','AUTHORIZED','UNAUTHORIZED','PERMITTED','FORBIDDEN','ALLOWED','PROHIBITED','LEGAL','ILLEGAL','LAWFUL','UNLAWFUL','LEGITIMATE','ILLEGITIMATE','VALID','INVALID','ACCEPTABLE','UNACCEPTABLE','APPROPRIATE','INAPPROPRIATE','SUITABLE','UNSUITABLE','FITTING','UNFITTING','PROPER','IMPROPER','CORRECT','INCORRECT','RIGHT','WRONG','TRUE','FALSE','ACCURATE','INACCURATE','PRECISE','IMPRECISE','EXACT','APPROXIMATE','SPECIFIC','GENERAL','PARTICULAR','UNIVERSAL','INDIVIDUAL','COLLECTIVE','PERSONAL','IMPERSONAL','PRIVATE','PUBLIC','SOCIAL','ANTISOCIAL','FRIENDLY','UNFRIENDLY','HOSTILE','AGGRESSIVE','PASSIVE','ASSERTIVE','BOLD','BRAVE','COURAGEOUS','FEARLESS','DARING','AUDACIOUS','INTREPID','VALIANT','HEROIC','GALLANT','STALWART','STOUT','STURDY','ROBUST','HARDY','HEALTHY','FIT','STRONG','MUSCULAR','ATHLETIC','GYMNASTIC','ACROBATIC','AGILE','NIMBLE','DEFT','DEXTEROUS','ADROIT','SKILLFUL','ADEPT','PROFICIENT','EXPERT','MASTER','VIRTUOSO','MAESTRO','GENIUS','PRODIGY','TALENT','GIFT','FLAIR','KNACK','APTITUDE','BENT','LEANING','PREDISPOSITION','PREDILECTION','PROPENSITY','PROCLIVITY','INCLINATION','TENDENCY','DISPOSITION','TEMPERAMENT','NATURE','CHARACTER','PERSONALITY','INDIVIDUALITY','IDENTITY','SELF','EGO','PERSONA','IMAGE','REPUTATION','STANDING','STATUS','POSITION','RANK','GRADE','LEVEL','CLASS','CATEGORY','TYPE','KIND','SORT','VARIETY','SPECIES','GENUS','FAMILY','GROUP','SET','COLLECTION','ASSEMBLAGE','AGGREGATE','COMPILATION','ANTHOLOGY','OMNIBUS','COMPENDIUM','SUMMARY','ABSTRACT','SYNOPSIS','OUTLINE','SKETCH','PROFILE','PORTRAIT','DEPICTION','REPRESENTATION','IMAGE','LIKENESS','SIMULACRUM','COUNTERFEIT','IMITATION','FAKE','FORGERY','REPLICA','REPRODUCTION','COPY','DUPLICATE','CLONE','CARBON','TWIN','MIRROR','ECHO','REFLECTION','REVERBERATION','RESOUND','RESONATE','VIBRATE','OSCILLATE','FLUCTUATE','WAVE','SURGE','SWELL','TIDE','CURRENT','STREAM','FLOW','RUN','RIVULET','BROOK','CREEK','RIVER','STREAM','WATERFALL','CASCADE','CATARACT','SPRAY','MIST','FOG','HAZE','SMOG','CLOUD','VAPOR','STEAM','FUME','SMOKE','SOOT','ASH','CINDER','EMBER','COAL','CHARCOAL','CARBON','GRAPHITE','DIAMOND','GEM','JEWEL','PEARL','RUBY','SAPPHIRE','EMERALD','TOPAZ','OPAL','AMETHYST','QUARTZ','CRYSTAL','MINERAL','ORE','METAL','IRON','STEEL','COPPER','BRASS','BRONZE','ALUMINUM','TIN','LEAD','ZINC','NICKEL','CHROME','PLATINUM','GOLD','SILVER','MERCURY','TITANIUM','TUNGSTEN','URANIUM','RADIUM','PLUTONIUM','COBALT','MANGANESE','MAGNESIUM','CALCIUM','SODIUM','POTASSIUM','LITHIUM','BARIUM','STRONTIUM','ALUMINUM','SILICON','PHOSPHORUS','SULFUR','CHLORINE','ARGON','NEON','HELIUM','HYDROGEN','OXYGEN','NITROGEN','FLUORINE','BROMINE','IODINE','ASTATINE','RADON','XENON','KRYPTON','SELENIUM','TELLURIUM','POLONIUM','BISMUTH','CADMIUM','GALLIUM','GERMANIUM','INDIUM','RHENIUM','RHODIUM','RUTHENIUM','SCANDIUM','TANTALUM','TECHNETIUM','THALLIUM','THORIUM','THULIUM','YTTERBIUM','YTTRIUM','ZIRCONIUM','ACTINIUM','AMERICIUM','BERKELIUM','CALIFORNIUM','CERIUM','CURIUM','DYSPROSIUM','EINSTEINIUM','ERBIUM','EUROPIUM','FERMIUM','FRANCIUM','GADOLINIUM','HAFNIUM','HOLMIUM','LANTHANUM','LAWRENCIUM','LUTETIUM','MENDELEVIUM','NEPTUNIUM','NOBELIUM','OSMIUM','PALLADIUM','PRASEODYMIUM','PROMETHIUM','PROTOACTINIUM','RADIOACTIVE','ISOTOPE','ATOM','MOLECULE','COMPOUND','ELEMENT','MIXTURE','SOLUTION','SOLVENT','SOLUTE','ACID','BASE','ALKALI','SALT','SUGAR','GLUCOSE','FRUCTOSE','SUCROSE','LACTOSE','MALTOS','STARCH','CELLULOSE','PROTEIN','AMINO','ACID','ENZYME','HORMONE','VITAMIN','MINERAL','NUTRIENT','CALORIE','FAT','CARBOHYDRATE','FIBER','WATER','HYDRATION','DEHYDRATION','NUTRITION','DIET','FOOD','MEAL','BREAKFAST','LUNCH','DINNER','SUPPER','SNACK','APPETIZER','ENTREE','DESSERT','BEVERAGE','DRINK','WATER','JUICE','SODA','POP','COKE','PEPSI','SPRITE','FANTA','MOUNTAIN','DEW','DR','PEPPER','SEVEN','UP','CANADA','DRY','GINGER','ALE','ROOT','BEER','CREAM','SODA','ORANGE','APPLE','GRAPE','CHERRY','STRAWBERRY','BLUEBERRY','RASPBERRY','BLACKBERRY','CRANBERRY','WATERMELON','CANTALOUPE','HONEYDEW','PINEAPPLE','MANGO','PAPAYA','GUAVA','PASSION','FRUIT','KIWI','BANANA','PLANTAIN','AVOCADO','OLIVE','TOMATO','CUCUMBER','SQUASH','ZUCCHINI','PUMPKIN','GOURD','MELON','CORN','MAIZE','WHEAT','OATS','BARLEY','RYE','MILLET','SORGHUM','QUINOA','AMARANTH','BUCKWHEAT','RICE','PASTA','NOODLE','SPAGHETTI','MACARONI','FETTUCCINE','LINGUINE','PENNE','RIGATONI','FUSILLI','FARFALLE','ORZO','COUSCOUS','BREAD','ROLL','BUN','LOAF','SLICE','CRUST','CRUMB','DOUGH','BATTER','FLOUR','YEAST','BAKING','POWDER','SODA','SALT','SUGAR','HONEY','SYRUP','MOLASSES','MAPLE','AGAVE','STEVIA','ASPARTAME','SUCRALOSE','SACCHARIN','CYCLAMATE','ACESULFAME','NEOTAME','ADVANTAME','MONK','FRUIT','ALLULOSE','XYLITOL','ERYTHRITOL','SORBITOL','MANNITOL','ISOMALT','MALTI','LACTITOL','TREHALOSE','TAGATOSE','RIBOSE','XYLOSE','ARABINOSE','LYXOSE','RIBULOSE','XYLULOSE','PSICOSE','SORBOSE','TAGATOSE','FRUCTOSE','GLUCOSE','GALACTOSE','MANNOSE','GULOSE','IDOSE','ALLOSE','ALTROSE','GLUCOSE','DEXTROSE','LEVULOSE','INVERT','SUGAR','CORN','SYRUP','HIGH','FRUCTOSE','CORN','SYRUP','MALTOSE','SUCROSE','LACTOSE','GALACTOSE','GLYCOGEN','STARCH','AMYLOSE','AMYLOPECTIN','CELLULOSE','HEMICELLULOSE','PECTIN','GUM','MUCILAGE','ALGINATE','CARRAGEENAN','AGAR','GELATIN','COLLAGEN','KERATIN','ELASTIN','FIBRIN','MYOSIN','ACTIN','TUBULIN','KERATIN','COLLAGEN','ELASTIN','FIBRIN','MYOSIN','ACTIN','TUBULIN','INSULIN','GLUCAGON','TESTOSTERONE','ESTROGEN','PROGESTERONE','CORTISOL','ADRENALINE','NORADRENALINE','DOPAMINE','SEROTONIN','MELATONIN','OXYTOCIN','VASOPRESSIN','GROWTH','HORMONE','THYROID','HORMONE','PARATHYROID','HORMONE','CALCITONIN','INSULIN','GLUCAGON','SOMATOSTATIN','GASTRIN','SECRETIN','CHOLECYSTOKININ','GIP','GLP','PYY','GHRELIN','LEPTIN','ADIPONECTIN','RESISTIN','VISFATIN','APELIN','CHEMERIN','OEMENTIN','VASPIN','PROGRANULIN','FETUIN','A','SELENOPROTEIN','P','TRANSTHYRETIN','RETINOL','BINDING','PROTEIN','ALBUMIN','GLOBULIN','FIBRINOGEN','PROTHROMBIN','PLASMINOGEN','COMPLEMENT','IMMUNOGLOBULIN','ANTIBODY','ANTIGEN','CYTOKINE','CHEMOKINE','INTERLEUKIN','INTERFERON','TUMOR','NECROSIS','FACTOR','GROWTH','FACTOR','TRANSFORMING','GROWTH','FACTOR','BETA','FIBROBLAST','GROWTH','FACTOR','PLATELET','DERIVED','GROWTH','FACTOR','EPIDERMAL','GROWTH','FACTOR','VASCULAR','ENDOTHELIAL','GROWTH','FACTOR','NERVE','GROWTH','FACTOR','BRAIN','DERIVED','NEUROTROPHIC','FACTOR','GLIAL','CELL','DERIVED','NEUROTROPHIC','FACTOR','NEUROTROPHIN','CILIARY','NEUROTROPHIC','FACTOR','GLIAL','CELL','LINE','DERIVED','NEUROTROPHIC','FACTOR','ARTEMIN','NEURTURIN','PERSEPHIN','GDNF','FAMILY','RECEPTOR','ALPHA','RET','RECEPTOR','TYROSINE','KINASE','LRRK','LRRK2','PARKIN','PINK','DJ','SNCA','ALPHA','SYNUCLEIN','BETA','SYNUCLEIN','GAMMA','SYNUCLEIN','MAPT','TAU','APP','AMYLOID','BETA','PSEN','PRESENILIN','SORL','SORLA','LRP','LOW','DENSITY','LIPOPROTEIN','RECEPTOR','RELATED','PROTEIN','APOE','APOLIPOPROTEIN','ABCA','ATP','BINDING','CASSETTE','TRANSPORTER']);

export function validateWord(word) {
  return COMMON_WORDS.has(word.toUpperCase());
}

export function generateRandomLetter() {
  const useVowel = Math.random() < 0.35;
  return useVowel 
    ? VOWELS[Math.floor(Math.random() * VOWELS.length)]
    : CONSONANTS[Math.floor(Math.random() * CONSONANTS.length)];
}

// Cascade tiles after word submission
export function removeTilesAndCascade(board, selectedCells, boardSize) {
  const newBoard = board.map(row => row.map(cell => ({ ...cell })));
  
  // Mark selected cells as empty
  selectedCells.forEach(cell => {
    newBoard[cell.row][cell.col] = { letter: '', specialType: null, isOutlaw: false };
  });
  
  // For each column, let tiles fall
  for (let col = 0; col < boardSize; col++) {
    let writeRow = boardSize - 1;
    const tiles = [];
    
    // Collect non-empty tiles from bottom to top
    for (let row = boardSize - 1; row >= 0; row--) {
      if (newBoard[row][col].letter) {
        tiles.push({ ...newBoard[row][col] });
      }
    }
    
    // Fill from bottom with existing tiles
    for (let row = boardSize - 1; row >= 0; row--) {
      const tileIndex = boardSize - 1 - row;
      if (tileIndex < tiles.length) {
        newBoard[row][col] = tiles[tileIndex];
      } else {
        // Generate new tile for top rows
        newBoard[row][col] = {
          letter: generateRandomLetter(),
          specialType: Math.random() < 0.12 ? SPECIAL_TILES[Math.floor(Math.random() * SPECIAL_TILES.length)] : null,
          isOutlaw: Math.random() < 0.08
        };
      }
    }
  }
  
  return newBoard;
}

// Check if outlaw tiles reached bottom
export function checkOutlawDanger(board, boardSize) {
  return board[boardSize - 1].some(cell => cell.isOutlaw);
}