import * as G from './engine.js';
import { drawLane, unproject } from './draw.js';
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function mountBowling(root, { api = null, identityName = 'You', initialCode = '', display = false, host = false, onExit = () => {}, onHostRoom = () => {} } = {}) {
  let game = null, room = null, seat = null, solo = false, alive = true, raf = 0, poll = null, offset = 0, busy = false, error = '', lastUI = '', lastPhase = '', audio = null, lastSeq = 0, muted = false;
  const aim = { start: 0, aim: -.035, spin: 0, power: .85, revengeX: 0, revengeZ: .82, sabotageX: 0, visible: true };
  const settings = { ...G.DEFAULTS };
  const saveSeat = s => { seat = s; try { localStorage.setItem('nb_seat_v1', JSON.stringify(s)); } catch { /* private browsing */ } };
  const beep = (hz = 440) => { if(muted)return; try { audio ||= new (window.AudioContext || window.webkitAudioContext)(); if (audio.state === 'suspended') audio.resume(); const o=audio.createOscillator(),gain=audio.createGain(); o.type='triangle';o.frequency.value=hz;gain.gain.setValueAtTime(.035,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.13);o.connect(gain);gain.connect(audio.destination);o.start();o.stop(audio.currentTime+.14); } catch { /* audio optional */ } };
  root.innerHTML = `<div class="nb-shell"><header class="nb-top"><button class="nb-back" data-action="exit" aria-label="Back to arcade">← ARCADE</button><div><small>TEXASNOMAD GAMES PRESENTS</small><h1>NOMADIC <em>BOWLING</em></h1></div><span class="nb-stamp">ROLL STRAIGHT<br>PLAY DIRTY</span></header><div class="nb-layout"><section class="nb-stage"><canvas aria-label="Live Nomadic Bowling lane, ball and pins"></canvas><div class="nb-live-status" role="status"></div><div class="nb-stage-label"></div></section><aside class="nb-panel"></aside></div><section class="nb-scores" aria-label="Ten-frame bowling scoreboard"></section><div class="nb-toast" role="alert" hidden></div><footer>Ten frames. Real bowling scores. One optional dirty twist. <button data-action="sound">SOUND ON/OFF</button></footer></div>`;
  const canvas=root.querySelector('canvas'),ctx=canvas.getContext('2d'),panel=root.querySelector('.nb-panel'),scoreboard=root.querySelector('.nb-scores'),status=root.querySelector('.nb-live-status'),stageLabel=root.querySelector('.nb-stage-label'),toast=root.querySelector('.nb-toast');
  const say = text => { error=text;toast.textContent=text;toast.hidden=!text; };
  const apply = d => { if (!alive) return; room=d.room;game=d.room?.game || null;offset=(d.room?.now || Date.now())-Date.now();onHostRoom(d.you?.isHost?d.room.code:'');if(d.you && seat)seat={...seat,id:d.you.id,isHost:d.you.isHost};lastUI='';renderUI(); };
  function renderMenu() {
    panel.innerHTML=`<div class="nb-eyebrow">THE FRONTIER HAS A NEW SPORT</div><h2>Classic lanes.<br>Dirty possibilities.</h2><p>Aim your roll, choose power, add spin. Play clean—or risk a precision sabotage shot and give your rival a revenge pinshot.</p><label>RULEBOOK<select data-setting="mode"><option value="brawl">BERNA Brawl · sabotage + revenge</option><option value="classic">Classic · pure bowling</option></select></label><label>ROOM<select data-setting="stage">${G.STAGES.map(s=>`<option value="${s.id}">${s.name}</option>`).join('')}</select></label><label>FORMAT<select data-setting="teams"><option value="false">Every bowler for themselves</option><option value="true">Two teams · combined scores</option></select></label><button class="nb-primary" data-action="solo">QUICK PLAY · VS CPU</button><button data-action="host">HOST A GAME · YOU PLAY TOO</button><div class="nb-join"><input aria-label="Five-letter room code" placeholder="ROOM CODE" maxlength="5"><button data-action="join">JOIN</button></div><details><summary>How the dirty tricks work</summary><p>Brawl gives each rival 3 sabotage charges for the whole match. Only one nominated opponent can fire each roll. Aim at the ball and fire 0.2 seconds before it crosses the pink gate. Miss and the charge is gone. Land it and the bowler gets 7 seconds for one precision pinshot, worth up to 2 extra pins in the SAME delivery. No free third bowling roll. Classic turns all tricks off.</p></details>`;
  }
  function scoreHTML(g) { return `<div class="nb-score-heading"><span>OFFICIAL SCORECARD</span><span>${g.settings.teams?`SPURS ${g.teamTotals[0]} · BANDITS ${g.teamTotals[1]}`:'TEN FRAMES · MAX 300'}</span></div><div class="nb-score-scroll"><table><thead><tr><th>BOWLER</th>${Array.from({length:10},(_,i)=>`<th>${i+1}</th>`).join('')}<th>TOTAL</th></tr></thead><tbody>${g.players.map(p=>`<tr class="${g.turn===p.id?'active':''}"><th style="--player:${p.color}">${esc(p.name)}${p.cpu?' <small>CPU</small>':''}${g.settings.teams?` <small>${p.team?'BANDITS':'SPURS'}</small>`:''}</th>${p.frames.map((a,i)=>`<td><div>${G.marks(a,i).map(m=>`<b>${m}</b>`).join('')}</div><span>${p.cumulative[i]??''}</span></td>`).join('')}<td class="nb-total">${p.total}</td></tr>`).join('')}</tbody></table></div>`; }
  function renderUI() {
    if (!game && !room) { renderMenu();scoreboard.innerHTML='';status.textContent='WELCOME TO THE NEON FRONTIER';return; }
    if (!game) {
      const mine=seat?.isHost;
      panel.innerHTML=`<div class="nb-eyebrow">YOUR TABLE IS OPEN</div><h2 class="nb-room-code">${esc(room.code)}</h2><p>Friends join at texasnomadgames.com/join. Everyone sees the lane on their own device. A big display is optional.</p><ul class="nb-roster">${room.roster.map(p=>`<li><i style="background:${p.color}"></i>${esc(p.name)} ${p.isHost?'· HOST':p.cpu?'· CPU':''}${mine&&!p.isHost?`<button data-action="kick" data-id="${esc(p.id)}" aria-label="Remove ${esc(p.name)}">×</button>`:''}</li>`).join('')}</ul>${mine?`<label>RULEBOOK<select data-setting="mode"><option value="brawl" ${room.settings.mode==='brawl'?'selected':''}>BERNA Brawl</option><option value="classic" ${room.settings.mode==='classic'?'selected':''}>Classic</option></select></label><label>ROOM<select data-setting="stage">${G.STAGES.map(s=>`<option value="${s.id}" ${room.settings.stage===s.id?'selected':''}>${s.name}</option>`).join('')}</select></label><label>FORMAT<select data-setting="teams"><option value="false" ${!room.settings.teams?'selected':''}>Free for all</option><option value="true" ${room.settings.teams?'selected':''}>Two teams</option></select></label><button data-action="cpu" ${room.roster.length>=8?'disabled':''}>+ ADD CPU BOWLER</button><button class="nb-primary" data-action="start" ${room.roster.length<2?'disabled':''}>OPEN THE LANES</button>`:seat?'<p>Seat reserved. Waiting for the host to open the lanes.</p>':display?'<p>Read-only display · no player controls.</p>':'<button class="nb-primary" data-action="take-seat">TAKE A SEAT</button>'}`;
      status.textContent='LOBBY · '+room.roster.length+' / 8 BOWLERS';scoreboard.innerHTML='';return;
    }
    const now=Date.now()+offset,p=game.players.find(p=>p.id===game.turn),me=game.players.find(p=>p.id===(solo?'you':seat?.id)),mine=me?.id===p.id;
    status.textContent=game.phase==='final'?'FINAL SCORE':`FRAME ${game.frame+1} · ${p.name} · ${game.phase==='aim'?'UP NEXT':game.phase==='rolling'?'BALL IN PLAY':game.phase==='revenge'?'REVENGE PINSHOT':'PIN COUNT'}`;
    scoreboard.innerHTML=scoreHTML(game);
    const base=`<div class="nb-eyebrow">${game.settings.mode==='classic'?'CLASSIC RULES':'BERNA BRAWL'} · ${game.settings.teams?'TEAM MATCH':'FREE FOR ALL'}</div><h2>${game.phase==='final'?'Final reckoning.':esc(p.name)}</h2>`;
    if (game.phase==='final') { const winners=game.players.filter(p=>game.winnerIds.includes(p.id));panel.innerHTML=base+`<p>${winners.length>1?'Winners':'Winner'}: <strong>${winners.map(p=>esc(p.name)).join(' & ')}</strong></p><div class="nb-final-score">${Math.max(...game.players.map(p=>p.total))}<small>TOP INDIVIDUAL SCORE</small></div>${solo?'<button class="nb-primary" data-action="solo">PLAY AGAIN</button>':seat?.isHost?'<button class="nb-primary" data-action="start">REMATCH</button><button data-action="lobby">BACK TO LOBBY</button>':''}<button data-action="menu">LEAVE THE LANES</button>`;return; }
    if (game.phase==='aim' && mine) panel.innerHTML=base+`<p>Find the pocket. Add a little hook. Make it count.</p>${[['start','POSITION',-.28,.28,.01],['aim','AIM',-.34,.34,.005],['spin','SPIN · LEFT / RIGHT',-1,1,.05],['power','POWER',.3,1,.01]].map(([k,l,min,max,step])=>`<label>${l}<output data-output="${k}">${aim[k].toFixed(2)}</output><input type="range" data-aim="${k}" min="${min}" max="${max}" step="${step}" value="${aim[k]}" aria-label="${l}"></label>`).join('')}<div class="nb-release-label">RELEASE · SEND IT IN THE CENTER ZONE</div><div class="nb-release"><i></i><b></b></div><button class="nb-primary" data-action="bowl">SEND IT →</button><p class="nb-hint">Aim sets your line; spin bends it. Time your release in the center zone. Aiming at the head pin from an angle usually beats a straight center hit.</p>`;
    else if (game.phase==='revenge' && mine) panel.innerHTML=base+`<div class="nb-revenge-title">THEY HIT YOU.<br>HIT BACK.</div><p>Tap a standing pin on the lane to aim. Time the moving crosshair, then fire your one pinshot. Up to 2 pins count in this delivery.</p><div class="nb-clock"></div><button class="nb-primary" data-action="revenge">FIRE PINSHOT</button>`;
    else if (game.phase==='rolling' && me?.id===game.attacker && me.charges && !game.delivery.attack) panel.innerHTML=base+`<h3 class="nb-pink">YOUR SABOTAGE WINDOW</h3><p>Line up the ball at the pink gate. Fire 0.2 seconds BEFORE it gets there. A hit gives ${esc(p.name)} a revenge shot.</p><label>AIM AT GATE<input type="range" data-aim="sabotageX" min="-.45" max=".45" step=".005" value="${aim.sabotageX}" aria-label="Sabotage aim"></label><div class="nb-charge">${me.charges} CHARGES LEFT</div><div class="nb-shot-progress"><i></i></div><div class="nb-row"><button data-action="sabotage-left">PUSH ←</button><button data-action="sabotage-right">PUSH →</button></div>`;
    else panel.innerHTML=base+`<p>${game.phase==='aim'?'Watch the lane. Your turn is coming.':game.phase==='revenge'?'Sabotage landed. The bowler has one revenge pinshot.':game.phase==='settling'?`${game.delivery.knocked.length} pins down this delivery.`:'Follow the ball. The lane is live on every device.'}</p>${me?`<div class="nb-your-seat">YOU · ${esc(me.name)}${game.settings.mode==='brawl'?`<small>${me.charges} sabotage charges left</small>`:''}</div>`:'<div class="nb-your-seat">READ-ONLY SPECTATOR</div>'}<div class="nb-clock"></div>${game.delivery?.attack?`<div class="nb-attack-result">${game.delivery.attack.resolved?(game.delivery.attack.hit?'SABOTAGE LANDED':'SABOTAGE MISSED'):'SABOTAGE INCOMING'}</div>`:''}`;
    panel.insertAdjacentHTML('beforeend',`<div class="nb-feed">${game.log.slice(-4).reverse().map(l=>`<p>${esc(l.text)}</p>`).join('')}</div>${seat?.isHost?'<button class="nb-small" data-action="lobby">END MATCH · LOBBY</button>':''}`);
    aim.visible=Boolean(mine&&game.phase==='aim');aim.sabotageVisible=Boolean(me?.id===game.attacker&&game.phase==='rolling'&&!game.delivery.attack);
    if (lastPhase!==game.phase && game.seq!==lastSeq && game.phase==='settling') beep(180+game.delivery.knocked.length*45);
    lastPhase=game.phase;lastSeq=game.seq;
  }
  async function send(type, payload={}) {
    if(busy||display)return;busy=true;say('');beep();
    try { if(solo){const r=G.act(game,'you',{type,...payload},Date.now());if(!r.ok)say(r.error);lastUI='';renderUI();}else{const d=await api.action(seat.code,seat.token,type,payload);apply(d);if(d.result?.ok===false)say(d.result.error);} }catch(e){say(e.message);}finally{busy=false;}
  }
  async function connect(code, token=null) {
    if(!api){say('Online rooms are unavailable in this preview. Try Quick Play.');return;}
    solo=false;clearTimeout(poll);
    const tick=async()=>{try{apply(await api.getRoom(code,seat?.code===code?seat.token:token));}catch(e){say(e.message);if(e.status===401||e.status===403||e.status===404){onHostRoom('');seat=null;game=null;room=null;lastUI='';renderUI();return;}}if(alive)poll=setTimeout(tick,game?.phase==='rolling'?180:game?350:1200);};await tick();
  }
  function quickPlay(){onHostRoom('');clearTimeout(poll);room=null;seat=null;solo=true;const players=[{id:'you',name:identityName,color:'#32e6ff'},{id:'cpu1',name:'Chrome Cassidy',cpu:true,color:'#ffb55b'}];if(settings.teams)players.push({id:'cpu2',name:'Neon Nell',cpu:true,color:'#f373ff'},{id:'cpu3',name:'Rusty Circuit',cpu:true,color:'#72ffc6'});game=G.createGame({players,settings,seed:Date.now(),now:Date.now()});lastUI='';renderUI();}
  const input=e=>{const k=e.target.dataset.aim;if(k){aim[k]=Number(e.target.value);const o=root.querySelector(`[data-output="${k}"]`);if(o)o.textContent=aim[k].toFixed(2);}const s=e.target.dataset.setting;if(s){const value=s==='teams'?e.target.value==='true':e.target.value;settings[s]=value;if(room&&seat?.isHost)send('settings',{[s]:value});}};
  const click=async e=>{const button=e.target.closest('[data-action]');if(!button||button.disabled)return;const a=button.dataset.action;
    if(a==='exit'){onExit();return;} if(a==='sound'){muted=!muted;button.textContent=muted?'SOUND: OFF':'SOUND: ON';if(muted)audio?.suspend().catch(()=>{});return;}
    if(a==='solo'){quickPlay();return;}if(a==='menu'){onHostRoom('');clearTimeout(poll);solo=false;game=null;room=null;seat=null;lastUI='';renderUI();return;}
    if(a==='host'){if(!api){say('Try Quick Play in this preview.');return;}try{const d=await api.createRoom(settings);saveSeat({code:d.roomCode,token:d.token,id:d.you.id,isHost:true});apply(d);connect(d.roomCode,d.token);}catch(e){say(e.message);}return;}
    if(a==='join'){const code=root.querySelector('.nb-join input').value.trim().toUpperCase();if(!/^[A-Z]{5}$/.test(code)){say('Enter the five-letter room code.');return;}seat=null;await connect(code);return;}
    if(a==='take-seat'){try{const d=await api.action(room.code,null,'join');saveSeat({code:room.code,token:d.token,id:d.playerId,isHost:false});apply(d);}catch(e){say(e.message);}return;}
    if(a==='bowl'){send('bowl',aim);return;}if(a.startsWith('sabotage-')){send('sabotage',{x:aim.sabotageX,push:a.endsWith('left')?-1:1});return;}if(a==='revenge'){send('revenge',{x:aim.revengeX,z:aim.revengeZ});return;}
    if(a==='lobby'&&game?.phase!=='final'&&!window.confirm('End this match and return everyone to the lobby?'))return;
    send(a==='cpu'?'addCpu':a==='kick'?'kick':a,{playerId:button.dataset.id});
  };
  const pointer=e=>{if(game?.phase!=='revenge'||display)return;const b=canvas.getBoundingClientRect(),p=unproject(e.clientX-b.left,e.clientY-b.top,b.width,b.height);aim.revengeX=G.clamp(p.x,-.45,.45);aim.revengeZ=G.clamp(p.z,.72,1.08);};
  root.addEventListener('input',input);root.addEventListener('change',input);root.addEventListener('click',click);canvas.addEventListener('pointerdown',pointer);
  function animate(){if(!alive)return;const now=Date.now()+offset;if(solo&&game)G.tick(game,now);const b=canvas.getBoundingClientRect(),ratio=Math.min(window.devicePixelRatio||1,2);if(canvas.width!==Math.round(b.width*ratio)||canvas.height!==Math.round(b.height*ratio)){canvas.width=Math.round(b.width*ratio);canvas.height=Math.round(b.height*ratio);}ctx.setTransform(ratio,0,0,ratio,0,0);const scene=game?(solo?G.view(game,now):game):{settings:room?.settings||settings,phase:'aim',phaseAt:now,standing:G.PIN_POSITIONS.map(p=>p.id)};drawLane(ctx,b.width,b.height,scene,now,aim);const key=game?`${game.phase}:${game.seq}:${game.turn}:${game.players.map(p=>p.charges).join(',')}:${game.delivery?.attack?.resolved}`:'';if(game&&key!==lastUI){lastUI=key;if(solo){const state=game;game=G.view(state,now);renderUI();game=state;}else renderUI();}const clock=root.querySelector('.nb-clock');if(clock&&game)clock.textContent=Math.max(0,Math.ceil((game.deadline-now)/1000))+'s';const meter=root.querySelector('.nb-release i');if(meter&&game)meter.style.left=(50+Math.sin((now-game.phaseAt)/530)*45)+'%';const progress=root.querySelector('.nb-shot-progress i');if(progress&&game?.delivery)progress.style.width=Math.min(100,(now-game.delivery.launchedAt)/game.delivery.duration*100)+'%';stageLabel.textContent=(G.STAGES.find(s=>s.id===scene.settings.stage)||G.STAGES[0]).name;raf=requestAnimationFrame(animate);}
  // Local games retain engine state; UI consumes the same public view as online.
  const originalRender=renderUI;
  renderUI=()=>{if(solo&&game&&game.randomState!==undefined){const state=game;game=G.view(state,Date.now());originalRender();game=state;}else originalRender();};
  renderUI();raf=requestAnimationFrame(animate);
  if(initialCode){try{const saved=JSON.parse(localStorage.getItem('nb_seat_v1')||'null');if(!display&&saved?.code===initialCode)seat=saved;}catch{/*ignore*/}connect(initialCode,seat?.token);}
  else if(host){let saved=null;try{saved=JSON.parse(localStorage.getItem('nb_seat_v1')||'null');}catch{/* storage optional */}if(saved?.isHost&&saved.code){seat=saved;connect(saved.code,saved.token);}else{const btn=panel.querySelector('[data-action="host"]');btn?.click();}}
  return ()=>{alive=false;cancelAnimationFrame(raf);clearTimeout(poll);root.removeEventListener('input',input);root.removeEventListener('change',input);root.removeEventListener('click',click);canvas.removeEventListener('pointerdown',pointer);audio?.close().catch(()=>{});root.replaceChildren();};
}
